name: attack_sam2
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.10 
  - numpy
  - matplotlib
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=12.1
  - pip
  - ipykernel
  - segment-anything
  - pip:
    - opencv-python